# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mult.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmult.proto\x12\x04\x63\x61lc\")\n\x0b\x43\x61lcRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1a\n\tCalcReply\x12\r\n\x05value\x18\x01 \x01(\x05\x32>\n\nCalculator\x12\x30\n\x08Multiply\x12\x11.calc.CalcRequest\x1a\x0f.calc.CalcReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mult_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALCREQUEST._serialized_start=20
  _CALCREQUEST._serialized_end=61
  _CALCREPLY._serialized_start=63
  _CALCREPLY._serialized_end=89
  _CALCULATOR._serialized_start=91
  _CALCULATOR._serialized_end=153
# @@protoc_insertion_point(module_scope)
